@startuml  
Persona <-- Alumno
Aula "0..*" o-- "1" Persona
class Aula {

}
abstract class Persona {
    - String nombre
    + getNombre(): String
    + setNombre(n: String)
}

class Alumno {
    - String direccion
}
@enduml