@Startuml Ejercicio18

'La clase FileOO2 se deberia implementar fisicamente? O en este caso seria un archivo? o la clase seria fisica tendriamos que asignarle las variables de instancia de algun modo, es algo que no me cierra.'

FileManager <|.. ArchivoOO2 
FileManager <|..Accessor
FileManager <-- Accessor : componente


Accessor <|-- Extension
Accessor <|-- Tamaño
Accessor <|-- FechaCreacion
Accessor <|-- FechaModificacion
Accessor <|-- Permisos

interface FileManager <<component>>{
    +prettyPrint():String 
}

class ArchivoOO2 <<concreteComponent>>{
    -nombre: String
    -extension: String 
    -tamaño: real 
    -fechaCreacion: Date 
    -fechaModificacion: Date 
    -permisos: String
    +prettyPrint():String
}

abstract class Accessor <<decorator>>{
    +prettyPrint():String
}

class Extension <<concreteDecorator>>{
    +prettyPrint():String    
}

class Tamaño <<concreteDecorator>>{
    +prettyPrint():String   
}

class FechaCreacion <<concreteDecorator>>{
    +prettyPrint():String   
}

class FechaModificacion <<concreteDecorator>>{
    +prettyPrint():String   
}

class Permisos <<concreteDecorator>>{
    +prettyPrint():String   
}

@enduml