@startuml Ejercicio20

Arma <|.. Espada
Arma <|.. Arco
Arma <|.. Baston
Armadura <|.. ArmaduraDeCuero
Armadura <|.. ArmaduraDeAcero
Armadura <|.. ArmaduraDeHierro
Personaje --> Arma : arma 
Personaje --> Armadura : armadura 
CreadorDePersonajes -> Personaje : personaje
CreadorDePersonajes <|-- CreadorDeArquero
CreadorDePersonajes <|-- CreadorDeGuerrero
CreadorDePersonajes <|-- CreadorDeMago
CreadorDePersonajes <|-- CreadorDeThoor
Constructor *-- CreadorDePersonajes : creador

'Estaba en la duda de hacer una Strategy con los personajes, pero entiendo que justamente tienen el nombre para Identificarse entonces lo mas sensato es hacer un Strategy de Armadura y la clase Personaje se diferencia de otra por su nombre.

'Para crear los personajes, uso un Builder? Pq deberia tener dos directores que indiquen el orden, ya que el mago tiene 2 habilidades y el guerrero 1 (Entiendo que el arquero tendria combate a distancia aunque no diga nada).

'BUILDER: NO INDICA LA CANTIDAD DE VECES QUE TIENE QUE HACER ALGO? OSEA SE SUPONE QUE EL MAGO POR EJEMPLO HACE DOS HABLIDADES Y EL GUERRERO UNA? PERO ESTO LO HARIA EN EL CONCRETO

interface Arma <<Strategy>>{
    +dañoA(ArmaduraCuero acu): Int 
    +dañoA(ArmaduraHierro ah): Int 
    +dañoA(ArmaduraAcero ace): Int 
}

class Espada <<ConcreteStrategy>>{
    +dañoA(ArmaduraCuero acu): Int 
    +dañoA(ArmaduraHierro ah): Int 
    +dañoA(ArmaduraAcero ace): Int 
}

class Arco <<ConcreteStrategy>>{
    +dañoA(ArmaduraCuero acu): Int 
    +dañoA(ArmaduraHierro ah): Int 
    +dañoA(ArmaduraAcero ace): Int 
}

Class Baston <<ConcreteStrategy>>{
    +dañoA(ArmaduraCuero acu): Int 
    +dañoA(ArmaduraHierro ah): Int 
    +dañoA(ArmaduraAcero ace): Int 
}

'El String seria para saber si gano o perdio? Aunque en realidad los dos reciben daño. Supuestamente el que ataca nada mas hace daño, en este caso.
'En vez de combatir le pongo atacar.
class Personaje{
    -nombre: String
    -habilidades: String[*]
    +atacar(Personaje p): String 
}

'Lo que me hace ruido, es que queda vacia porque no tiene una defenesa o un algo que le pueda aplicar. 
'Sino que hago, lo identifico por un String?
'Pq encima no tienen algo que sea defensa contra 
interface Armadura <<Strategy>>{ 
    +recibirDaño(Arma a)

}

class ArmaduraDeCuero <<ConcreteStrategy>>{
    +recibirDaño(Arma a)
}

class ArmaduraDeHierro <<ConcreteStrategy>>{
    +recibirDaño(Arma a)
}

class ArmaduraDeAcero <<ConcreteStrategy>>{
    +recibirDaño(Arma a)
}

'Utilizo varios metodos debido al orden y cantidad de armas/habilidades. Se pueden usar varios metodos de esta forma en un director o un director es igual a un metodo/orden.
'El ConstruirPersonajeADistancia seria para Mago y Thoor
class Constructor <<Director>>{
    +ConstruirPersonaje(): Personaje
}

abstract class CreadorDePersonajes <<Builder>>{
    +EmpezarCreacion(Personaje p)
    +AsignarArma(Personaje p)
    +AsignarHabilidad(Personaje p)
    +AsignarArmadura(Personaje p)
    +FinalizarCreacion() : Personaje
}

class CreadorDeGuerrero <<ConcreteBuilder>>{
    +AsignarArma(Personaje p)
    +AsignarArmadura(Personaje p)
    +AsignarHabilidad(Personaje p)
}

class CreadorDeArquero <<ConcreteBuilder>>{
    +AsignarArma(Personaje p)
    +AsignarArmadura(Personaje p)
    +AsignarHabilidad(Personaje p)
}

class CreadorDeMago <<ConcreteBuilder>>{
    +AsignarArma(Personaje p)
    +AsignarArmadura(Personaje p)
    +AsignarHabilidad(Personaje p)
}

class CreadorDeThoor <<ConcreteBuilder>>{
    +AsignarArma(Personaje p)
    +AsignarArmadura(Personaje p)
    +AsignarHabilidad(Personaje p)
}

@enduml